apiVersion: v1
kind: Pod
metadata:
  name: foodsystem-app
  labels:
    app: foodsystem-app
spec:
  containers:
#  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
  - image: "foodappregistry.azurecr.io/food-app:latest"
    name: foodsystem-image
    ports:
    - containerPort: 80
      protocol: TCP
  imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: foodsystem-service
spec:
  selector:
    app: foodsystem-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodsystem-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: foodsystem-service
            port:
              number: 80
        pathType: Exact

